function [ spectrum ] = calculateAbsoluteIrradiance(fiberdiameter, calibrationFile, spectrumFile, darkSpectrumFile)
%CALCULATEABSOLUTEIRRADIANCE Calculate the absolute irradiance by applying calibration data to a raw spectrum
% Uses the calibration data as generated by the createCalibrationFile()
% function. It is advised to measure the raw spectrum using an averaging of
% 30 and a boxcar width of 5 to obtain the best results.

%% Initialization
calibrationDirectory = '';
spectrumDirectory = '';
darkSpectrumDirectory = '';

%% Enter the fiber diameter
if (~exist('fiberdiameter', 'var'))
    fiberdiameter = inputdlg('Enter fiber diameter [cm]', 'Fiber diameter' , 1, {'0'});
    fiberdiameter = str2num(fiberdiameter{1});
end
%% Load the calibration data
if (~exist('calibrationFile', 'var'))
    [calibrationFile calibrationDirectory] = uigetfile({'*.mat';'*.*'}, 'Select the calibration data');
end
load(strcat(calibrationDirectory, calibrationFile));

%% Load the spectrum
if (~exist('spectrumFile', 'var'))
    [spectrumFile spectrumDirectory] = uigetfile({'*.txt';'*.*'}, 'Select the smoothed spectrum');
end
spect = importdata(strcat(spectrumDirectory, spectrumFile));
Sp = spect.data;

% Load the dark spectrum
if (~exist('darkSpectrumFile', 'var'))
        [darkSpectrumFile darkSpectrumDirectory] = uigetfile({'*.txt';'*.*'}, 'Select the smoothed dark spectrum');
end
darkSpect = importdata(strcat(darkSpectrumDirectory, darkSpectrumFile));
Dp = darkSpect.data;

% Find the integration time
IndexC = strfind(lower(spect.textdata), 'integration time');
Index = find(not(cellfun('isempty', IndexC)));
T = textscan(lower(spect.textdata{Index}), 'integration time (usec): %f'); % usec
T = T{1}/1e6;   % [s]

dLp = Sp(2,1) - Sp(1,1);    % Wavelength spread [nm]
A = (fiberdiameter/2)^2*pi; % Collection area [cm^2]
I = calibrationData.ujoulepercount .* (Sp(:,2) - Dp(:,2))/(T * A * dLp);  % Irradiance [uW/nm/cm^2]

%% Plot the calculated absolute irradiance
plot(Sp(:,1), I);
xlabel('Wavelength [nm]', 'Interpreter', 'latex');
ylabel('Absolute irradiance [$\mathrm{\mu W/cm^2/nm}$]', 'Interpreter', 'latex');

spectrum.wavelength = Sp(:,1);
spectrum.I = I;

end

